### ISSUE TITLE
Latest version of Packer doesn't work

### ISSUE THREAD

**Issue by GeoWill** [DemocracyClub/ee_deploy#41]
Tried with version 1.5.1 and got:
```
invalid 'ami_name': template: root:1: function "clean_ami_name" not defined in:
ee {{isotime |clean_ami_name }}
```
It worked with 0.12.3 downloaded from https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip

**Comment by chris48s** [comment]
With this issue, we should look at updating the scripts for 

https://github.com/DemocracyClub/who_deploy
https://github.com/DemocracyClub/polling_deploy

at the same time so we they all work with a single global install of packer.

**Comment by symroe** [comment]
We've got around this by moving from packer on dev machines to AWS Image Builder.
